### ISSUE TITLE
Can not finish write a xls file

### ISSUE THREAD

**Issue by chuanhtuan** [zdavatz/spreadsheet#103]
require 'spreadsheet'
book = Spreadsheet.open('/home/xxx/test/test.xls')
sheet = book.worksheet 0
sheet.row(11).replace [1, 'aaa']
book.write '/home/xxx/test/out.xls'  <-- block here

'book.write' can not finish, it's blocked
if I only open file and write out, it's OK
but, when I modify by using replace method (or others), it's blocked
Please help me, thanks!

**Comment by prosanes** [comment]
I had this problem when all my columns were with a grey background, even though it didn't have data. The gem was just taking too long to write.
