### ISSUE TITLE
Custom format breaks on 48th use in Excel 2013

### ISSUE THREAD

**Issue by DouweM** [zdavatz/spreadsheet#115]
- Put this in `wtf.rb`:
  
  ``` ruby
  #!/usr/bin/env ruby
  
  require "spreadsheet"
  
  workbook = Spreadsheet::Workbook.new
  sheet = workbook.create_worksheet
  
  48.times do |i|
    row = sheet.row(i)
  
    row.update_format 0, number_format: "yyyy-mm-dd"
  
    row[0] = i
  end
  
  File.open("wtf.xls", "w") { |file| workbook.write(file) }
  ```
- Install the spreadsheet gem, set `wtf.rb` to be executable and execute it:
  
  ``` sh
  gem install spreadsheet
  chmod +x wtf.rb
  ./wtf.rb
  ```
- Open the newly created `wtf.xls` using Excel 2013.
- Make the first column slightly wider if you see a bunch of "#########"'s.
- Witness something amazing:
  ![screen shot 2014-11-28 at 14 30 23](https://cloud.githubusercontent.com/assets/159434/5228498/1fb1210a-770b-11e4-9caa-faefa028c66d.png)

I've put the 48 uses in separate rows, but it also works if you put them in columns or in a 6x8 block or whatever.

Everything is fine if you use `sheet.column(0).default_format = Spreadsheet::Format.new(number_format: "yyyy-mm-dd")` which is nicer anyway, but this still looks like a bug to me!

**Comment by varunDM** [comment]
@DouweM Have you found any fix for this issue?

**Comment by DouweM** [comment]
@varunDM I opted to set the format for the entire column instead of the individual  cells.

**Comment by varunDM** [comment]
@DouweM OK. But I'm only familiar with setting format as follows:
`@sheet.row(@count).set_format(col_index, format)`
Is there anyway to set format for the entire column?

**Comment by varunDM** [comment]
@DouweM Cool. Thanks!

**Comment by zdavatz** [comment]
thanks for sharing!

**Comment by varunDM** [comment]
@DouweM Thanks for that. But what if I wanted to make some intermediate rows bold?

**Comment by zdavatz** [comment]
Check the Guide. https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md
