### ISSUE TITLE
Duplicate/repeated Spreadsheet::Formats not working in Excel 2013 for Windows

### ISSUE THREAD

**Issue by chellberg** [zdavatz/spreadsheet#120]
Encountered an issue when using roo-xls/spreadsheet to generate a .xls file with alternating row color/shading. Each row has its style set by referencing this method:
```ruby
def self.value_format(index)
  color = index.odd? ? :silver : :white
  Spreadsheet::Format.new(
    :horizontal_align => :center,
    :vertical_align   => :top,
    :shrink           => true,
    :pattern_fg_color => color,
    :pattern          => 2,
    :border           => :thin,
    :size             => 11
  )
end
```

The resulting file looks fine in Excel 2011 for OS X and earlier versions of Excel for Windows, but on Excel 2013/Windows 8 all formatting below row 24 is missing.

![screenshot](https://cloud.githubusercontent.com/assets/4022252/5744994/758773b0-9bf3-11e4-833b-61f33737edf6.png)

A coworker hypothesized that this might be the result of some kind of limit on the number of repeated, identical formats in Excel 2013 and/or the way formats are applied in the spreadsheet gem. A test using this modified code
```ruby
def self.value_format(index)
    color = index > 55 ? :white : "xls_color_#{index}".to_sym
    Spreadsheet::Format.new(
      :horizontal_align => :center,
      :vertical_align   => :top,
      :shrink           => true,
      :pattern_fg_color => color,
      :pattern          => 2,
      :border           => :thin,
      :size             => 11
    )
  end
```

produced these results (in Excel 2013, Windows 8) 

![image](https://cloud.githubusercontent.com/assets/4022252/5745064/fb0e9bb2-9bf3-11e4-9d2f-436d2c334f1a.png)

which I believe confirms that the issue has to do with repeated/alternated, identical Spreadsheet::Formats.

**Comment by zdavatz** [comment]
Can you pleaes provide me with a full script via gist.github.com and also link your files here in some way. How where the XLS files created in the first place? What happens if you open the files with LibreOffice?

**Comment by kameshprasad** [comment]
Facing the same issue, formatting is working fine with MS Office version earlier to 2013 and in LibreOffice as well. 
Here's the screenshot of the same: http://grab.by/F8J2

**Comment by zdavatz** [comment]
Can you please link your test code and your sample files here, so I can have a look at them. Thanks!

**Comment by adamcooke** [comment]
In the absence of any additional information from @chellberg, I've prepared a quick script to demo this. The gist linked below will generate the screenshot shown below. It certainly looks like a limitation in Excel 2013. It looks fine in other versions of Excel on other platforms. I hope that helps.

https://gist.github.com/adamcooke/bc0f0e687d4712073a02

![Screenshot](https://s.adamcooke.io/15/w3x4NZvZxK.png)

**Comment by chellberg** [comment]
Sorry about that @zdavatz - I missed your replies. Thanks for putting that gist together, @adamcooke.

**Comment by kameshprasad** [comment]
Thanks @zdavatz <https://github.com/zdavatz>, Thanks for following up and
putting gist.

Bests,
Kamesh

On Mon, Aug 17, 2015 at 11:57 PM, Corin Chellberg <notifications@github.com>
wrote:

> Sorry about that @zdavatz <https://github.com/zdavatz> - I missed your
> replies. Thanks for putting that gist together, @adamcooke
> <https://github.com/adamcooke>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zdavatz/spreadsheet/issues/120#issuecomment-131917772>
> .
>



-- 

*Best Regards,*

*Kamesh Prasad | Ruby on Rails developer*
  [image: PlumSlice] PlumSlice Labs
Email: kprasad@plumslice.com | Skype: kamesh.plumslice
Office Address: 632-634, 6th floor Tower A Spaze IT Park Sector-49
Gurgaon-Sohna Road Gurgaon, Haryana-122002, India
Mobile: +91-9999577239 | Web: www.PlumSlice.com <http://www.plumslice.com>

**Comment by zdavatz** [comment]
Quote @adamcooke 
```
It certainly looks like a limitation in Excel 2013. It looks fine in other versions of Excel on other platforms.
```

**Comment by varunDM** [comment]
So there's no solution for this??

**Comment by adamcooke** [comment]
The solution is to cache the format instances and apply existing instances to cells using `set_format`.

```ruby
format1= Spreadsheet::Format.new(:pattern => 1, :pattern_fg_color => :silver, :bottom => :thin, :top => :thin, :left => :thin, :right => :thin)
format2 = Spreadsheet::Format.new(:pattern => 1, :pattern_fg_color => :white, :bottom => :thin, :top => :thin, :left => :thin, :right => :thin)

worksheet.row(i).set_format(0, format1)
worksheet.row(i).set_format(1, format2)
worksheet.row(i).set_format(2, format1)
```

**Comment by zdavatz** [comment]
Ok, thanks for sharing this!

**Comment by InteNs** [comment]
@adamcooke this fixes the issue, is there another way where the `update_format` method could be used? (we draw some lines on the sheet after initial formatting, these lines will display on other cells also using the same cached format instances

**Comment by InteNs** [comment]
i've fixed the issue with the following code:
```rb
    def register_format(format)
      # build a kv store with the format hash as key and the format object as value
      @formats ||= {}
      unless @formats.key?(format)
        @formats[format] = ::Spreadsheet::Format.new(format)
      end
      @formats[format]
    end

    def format_cell(row_index, column_index, **format)
      row = sheet.row(row_index)

      new_format = if row.formats[column_index].present?
                     # existing format, clone it and update the clone
                     row.format(column_index).clone.update_format(**format)
                   else
                     # no format here, grab a cached or new format
                     register_format(format)
                   end

      row.set_format(column_index, new_format)
    end

```

**Comment by zdavatz** [comment]
great, thank you for reporting!

**Comment by InteNs** [comment]
still had some issues with even larger excel files, updated the code as follows:
```rb
    def register_format(format)
      @formats ||= {}
      unless @formats.key?(format)
        @formats[format] = ::Spreadsheet::Format.new(format)
      end
      @formats[format]
    end

    def format_cell(row_index, column_index, **format)
      row = sheet.row(row_index)

      if row.formats[column_index].present?
        # existing format, clone it and update the clone
        existing_format, obj = @formats.find { |_, v| v == row.formats[column_index] }

        if existing_format.present?
          # we found the format combination, now merge it
          format = existing_format.merge(format)

          unless @formats.key?(format)
            # if the merged format hasn't been used before, register it
            obj = obj.clone.update_format(**format)
            @formats[format] = obj
          end
        end
      end

      row.set_format(column_index, register_format(format))
    end

```

**Comment by zdavatz** [comment]
even better!
