### ISSUE TITLE
spreadsheet don't handle excel limit, which may generate an xls file cannot be opened by excel.

### ISSUE THREAD

**Issue by hachiwang** [zdavatz/spreadsheet#122]
For example, for all versions of Microsoft Excel, a cell can contain up to 32,767 characters.

**Comment by zdavatz** [comment]
Ok, please provide me with a sample script via gist.github.com and your sample file. Please link them both here.

**Comment by hachiwang** [comment]
https://gist.github.com/hachiwang/43236c4f5ab66885b1c4

**Comment by zdavatz** [comment]
this seems to be an XLS issue. I can open both files with my Libreoffice 4.3.4.1 on Linux.

**Comment by hachiwang** [comment]
But test1.xls cannot be opened by any version of Microsoft Office software. Do you have any suggestions here?

**Comment by zdavatz** [comment]
What version of Microsoft Office are you using and what operating system?

**Comment by zdavatz** [comment]
Have you tried it with LibreOffice?

**Comment by hachiwang** [comment]
I'm using the OSX 10.9.5 and MS Office 2011. 
I'm sure there will be no problem for LibreOffice, because this is a MS Office Excel limitation.

**Comment by zdavatz** [comment]
Sorry I have no further ideas at the moment. I think MS XLS has its limitations.

**Comment by zdavatz** [comment]
If you have a patch I am happy to test it.
