### ISSUE TITLE
number_format  = 'MM/DD/YYYY' not working for Microsoft Excel 2011@OS X10.9

### ISSUE THREAD

**Issue by hachiwang** [zdavatz/spreadsheet#123]
After setting number_format to "MM/DD/YYYY", Microsoft Excel 2011 still show the date format as "MM-DD-YYYY". But Apache OpenOffice 4.1 works ok. Is Microsoft Excel doing something tricky stuff here?
Thanks.
Refer to:
https://gist.github.com/hachiwang/43236c4f5ab66885b1c4#file-number_format-rb
PS: Tried other number_format like "MM:DD:YYYY", "MM|DD|YY", both Apache OpenOffice 4.1 and Microsoft Excel work.  It seems "/" is some kinda of special character here. Is there anything I missed here?

**Comment by hachiwang** [comment]
Ok. After comparing the binary code,  "/" is indeed some kinda of special character here. 
After setting to number_format = "MM\\/DD\\/YYYY", Microsoft Excel 2011 works.

**Comment by zdavatz** [comment]
Ok, thank you for reporting this!
