### ISSUE TITLE
Allow access to rendered output instead of just writing a file

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [zdavatz/spreadsheet#125]
I'm using Rails and in my controller I simply wish to output the contents of the xls file directly inside the view partial instead of using the disk and having to:

1) Write the file  
2) Read the file contents  
3) Destroy the original file  
4) Output the file contents

---

controller
``` ruby
def index
    respond_to do |format|
      format.html
      format.xls {
        @workbook = Spreadsheet::Workbook.new
      }
    end
  end
```

app/views/invoices/index.xls.erb
``` ruby
<%=

summary = @workbook.create_worksheet(name: 'Summary')
# More to do here...

# @stats.items => [{
#   category => {
#     item_name => {
#       price => {
#         id, inventory, quantity, tax_added, tax_included, discounts, 
#         subtotal, total, base_price, effective_base_price, 
#       }
#     }
#   }
# }]
@stats.items.each do |category|
  ws = @workbook.create_worksheet(name: category)
  xls_write_headings ws # helper method...
end

# This part is rather unnecessary...I should be able to do something like: @workbook.file_contents
loc = Rails.root.join('tmp', "invoices-#{ SecureRandom.uuid }.xls")
@workbook.write loc
contents = File.read(loc)
File.delete loc
contents
%>
```

**Comment by zdavatz** [comment]
you mean you want to leave the contents of the file in the memory?

**Comment by JakeTheSnake3p0** [comment]
Yes; I'd like a public method that will produce an IO/File object in-memory so that the disk is never touched.

**Comment by zdavatz** [comment]
That is not so simple. Please send us a patch if you have one. We will be happy to verify it.

**Comment by JakeTheSnake3p0** [comment]
I found another way around it:

```ruby
file_contents = StringIO.new
view_context.write_excel_format file_contents
send_data file_contents.string.force_encoding('binary'), filename: "the-output-file.xls"
```

**Comment by zdavatz** [comment]
great! Thanks for documenting this! I will!

**Comment by zdavatz** [comment]
Done, see: https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md#allow-access-to-rendered-output-instead-of-just-writing-a-file

Thanks again!

**Comment by JakeTheSnake3p0** [comment]
Whoops - I didn't think you would copy/paste my answer. This will confuse people as the line `view_context.write_excel_format` is rails-specific and specific to my app only. Here's a more appropriate snippet to post in the guide:

#To avoid hitting the disk (i.e., write to memory)
```ruby
file_contents = StringIO.new
book.write file_contents # => Now file_contents contains the rendered file output
```

**Comment by zdavatz** [comment]
done. thanks!

**Comment by AndyObtiva** [comment]
This is great! `.force_encoding('binary')` totally saved me in sending as email attachment that opens up in Excel successfully. Thanks!

**Comment by zdavatz** [comment]
Cool!

**Comment by zhangw** [comment]
It was the first time that I used spreadsheet moudle to generate content of xls format, and also I have the same requirement to output data from memory directly without writing to disk. I just viewed the source code of spreadsheet, and I found the parameter named "io_or_path" which caused me try “StringIO.new”
in my case, It was OK. Cool!

**Comment by zdavatz** [comment]
Thank you for sharing this here!

**Comment by markedmondson** [comment]
If anyone else stumbles across this, the `file_contents.seek(0)` was critical for me in sending an Excel attachment via StringIO.

```
> output.read
=> "\t\b\x10\x00\x00\x06\x05\x00\xBB\r\xCC\a\x00\x00\x00\x00\x06\x00\x00\x00B\x00\x02\x00\x12Ra\x01\x02\x00\x00\x00=\x01\x02\x00\x01\x00\x12\x00\x02\x00\x00\x00\x13\x00\x02\x00\x00\x00=\x00\x12\x00\x00\x00\x00\x00\x00@\x00 8\x00\x00\x00\x00\x00\x01\x00\xE5\x00\"\x00\x02\x00\x00\x00\x0E\x00\x02\x00\x01\x00\xB7\x01\x02\x00\x00\x00\xDA\x00\x02\x00\x00\x001\x00\x15\x00\xC8\x00\x00\x00\xFF\x7F\x90\x01\x00\x00\x00\x02\x01\x00\x05\x00Arial\x1E\x04\f\x00\xA4\x00\a\x00\x00GENERAL
```
vs

```
> output.read
=> "\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00;\x00\x03\x00\xFE\xFF\t\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\xCA\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\xCB\x00\x00\x00\x01\x00\x00\x00\xFE\xFF\xFF\xFF\x00\x00\x00\x00\xCC\x00\x00\x00\xCD\x00\x00\x00\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\t\b\x10\x00\x00\x06\x05\x00\xBB\r\xCC\a\x00\x00\x00\x00\x06\x00\x00\x00B\x00\x02\x00\x12Ra\x01\x02\x00\x00\x00=\x01\x02\x00\x01\x00\x12\x00\x02\x00\x00\x00\x13\x00\x02\x00\x00\x00=\x00\x12\x00\x00\x00\x00\x00\x00@\x00 8\x00\x00\x00\x00\x00\x01\x00\xE5\x00\"\x00\x02\x00\x00\x00\x0E\x00\x02\x00\x01\x00\xB7\x01\x02\x00\x00\x00\xDA\x00\x02\x00\x00\x001\x00\x15\x00\xC8\x00\x00\x00\xFF\x7F\x90\x01\x00\x00\x00\x02\x01\x00\x05\x00Arial\x1E\x04\f\x00\xA4\x00\a\x00\x00GENERAL
```

It looks like the header was getting lost which caused Excel to throw:

> Excel could not open filename.xls because some content is unreadable. Do you want to open and repair this workbook?

**Comment by zdavatz** [comment]
Thank you for sharing this here.

**Comment by joshuapinter** [comment]
@markedmondson You can also use the built-in [`rewind()`](http://ruby-doc.org/stdlib-1.9.3/libdoc/stringio/rdoc/StringIO.html#method-i-rewind) method for putting the read index back at the beginning: 

```ruby
output.rewind
output.read
```

**Comment by joshuapinter** [comment]
I can't seem to get this to work without issue without writing to the file.

When I use `StringIO` as instructed here everything seems to work and the `.xls` file is downloaded. However, the byte size of the file is slightly off and when opening it I get the following message from Excel: 

![screenshot 2018-02-27 11 07 31](https://user-images.githubusercontent.com/180819/36746110-ba71a340-1bae-11e8-8502-05582e2dbb90.png)

When I click Yes it opens it and gives me this message: 

![screenshot 2018-02-27 11 07 34](https://user-images.githubusercontent.com/180819/36746147-d03e83fa-1bae-11e8-8fa8-4c27b695ad7b.png)

When I click View it shows me an xml file with the following error summary: 

`Excel recovered your formulas and cell values, but some data may have been lost.`

The Excel file opens up and it looks good after that.

If I use `.write( test1.xls )` it works great without any warnings or errors.

Am I missing something?

Thanks.

**Comment by joshuapinter** [comment]
I found what I was missing.... 

I was rendering these .xls views in a Rails view in order to keep things nice and clean and out of my Controller. However, I needed to add the [`raw`](https://apidock.com/rails/ActionView/Helpers/OutputSafetyHelper/raw) view helper or add the [`.html_safe`](https://apidock.com/rails/String/html_safe) to the string bring outputted in order for the output not to be sanitized and muck up the file contents.

**`raw`**
`<%= raw output %>`

**`html_safe`**
`<%= output.html_safe %>`

Doing one of these results in a perfect `.xls` output and everybody is happy again.

**Comment by zdavatz** [comment]
Well great :). Thank you for documenting this.

**Comment by joshuapinter** [comment]
Here's a complete example of how to allow users to download a `.xls` file without creating an actual file, and generate the actual `.xls` content in a View to keep the Controller clean:

**controllers/tasks_controller.rb**
```ruby
def index
  @tasks = Task.all

  respond_to do |format|
    format.html
    format.xls { set_file_name "tasks.xls" }
  end
end
```

**views/tasks/index.xls**
```ruby
<%=
workbook = Spreadsheet::Workbook.new
worksheet = workbook.create_worksheet

worksheet.row(0).replace( [ "Task Name", "Due On" ] )

@tasks.each_with_index do |task, index|
  row_number = index + 1

  worksheet.row( row_number ).replace( [ task.name, task.due_on ] )
end

file = StringIO.new

workbook.write( file )

file.string.html_safe
%>
```

By going to `/tasks.xls` in your browser it will automatically download the `tasks.xls` file.

**Comment by zdavatz** [comment]
Thanks, this is great!

**Comment by dduqueti** [comment]
@markedmondson and @joshuapinter Thank you! 🚀
