### ISSUE TITLE
No method to insert columns?

### ISSUE THREAD

**Issue by ShadowVariable** [zdavatz/spreadsheet#128]
Is there any way to insert a column? I have an array I want to insert as a column but I only see methods to insert rows.

**Comment by zdavatz** [comment]
Read the Guide: https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md

**Comment by dgilperez** [comment]
I did and honestly did not find an answer ... "not supported", is it?

**Comment by zdavatz** [comment]
I guess not really. You basically need to write a new file with all the data.

**Comment by zdavatz** [comment]
But see the modify part in the Guide: https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md#writing-is-easy

**Comment by dgilperez** [comment]
Thanks for the response. I ended up using `Matrix` to build a matrix with the columns, and then `.transpose` it to have rows. Not pretty, not useful in most cases, but it did for me. I guess other approaches with `sheet.row(X).insert Y` would also work.

**Comment by zdavatz** [comment]
Thank you for sharing your solution. Please continue to do so.
