### ISSUE TITLE
Can't load the gem spreadsheet 1.0.3

### ISSUE THREAD

**Issue by icehaku** [zdavatz/spreadsheet#132]
Can't use the gem, after install:

Cannot load such file -- spreadsheet
Extracted source (around line #224):

def consolidado
#224 || require 'spreadsheet'

or

uninitialized constant (~ControlerName~)Controller::Spreadsheet
Extracted source (around line #224):

def consolidado
#224 || raise book = Spreadsheet::Workbook.new.inspect

**Comment by zdavatz** [comment]
Send me your script please, so I can test.
