### ISSUE TITLE
Spreadsheet with Ruby 2.1.5

### ISSUE THREAD

**Issue by enorziana** [zdavatz/spreadsheet#133]
I am using spreadsheet v0.7.5.

Can spreadsheet works with Ruby 2.1.5? I recently upgraded my ruby version from 1.9.3 to 2.1.5, and all sorts of problems arises since then. I just wanted to clarify if changing my ruby to 2.1.5 is the cause to it. 

Please verify if spreadsheet does/does not support ruby 2.1.5. Would appreaciate your feedback the soonest you can. Thanks

Note: Among the problem is "Excel found unreadable content in 'XXXX.xls"......"

**Comment by zdavatz** [comment]
Please try again with Ruby 2.2.0. Also link your test file here so I can test it. I will also need a test script from you.

**Comment by enorziana** [comment]
Is there other option that I can try other than using Ruby 2.2.0? If I were to fork the gem, which area do you suggest me to work on?

Thank you!

**Comment by zdavatz** [comment]
What about Ruby 2.1.1. Does that work? Ruby can be quite inconsistent between version changes at times. See: https://travis-ci.org/zdavatz/spreadsheet
