### ISSUE TITLE
undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by yalmasri** [zdavatz/spreadsheet#134]
Hi
when trying installing spreadsheet, it gives an error:

D:\Sites\vm>gem install spreadsheet
ERROR:  Error installing spreadsheet:
        invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/cache/spreadsheet-1.0.3.gem

**Comment by zdavatz** [comment]
try again with Ruby 2.2.1.
