### ISSUE TITLE
Please consider providing a way to find out which colours are predefined.

### ISSUE THREAD

**Issue by shevegen** [zdavatz/spreadsheet#145]
Hello.

I was trying to use :slateblue as colour.

For instance:

```
  format = Spreadsheet::Format.new :color => :slateblue,
                                   :weight => :bold,
                                   :size => 14
```

Spreadsheet told me this error:

spreadsheet-1.0.5/lib/spreadsheet/datatypes.rb:109:in `block (2 levels) in colors': unknown color 'slateblue' (ArgumentError)

Would it be possible to feedback a way of supported and available colours? (:slateblue I tried to
use as it may be a "web colour"; the tutorial mentions :blue which is working, so I was trying
to see whether I could use :slateblue as well).

E. g. colour inbuilts?

The syntax could be, to give an example:

  Spreadsheet::Format.colours
  Spreadsheet::Format.colors

Or perhaps something such as:

  Spreadsheet.available_colours?

If this is not a useful addition feel free to just close it.

Thanks for reading!

**Comment by zdavatz** [comment]
I am always happy to test a patch. Most important is, that all the tests will pass on Travis.

**Comment by zdavatz** [comment]
have you seen: https://github.com/zdavatz/spreadsheet/search?q=colors&type=Issues&utf8=%E2%9C%93

**Comment by hqsiswiliam** [comment]
Maybe you can try the color list on:
http://www.softwaremaniacs.net/2013/11/setting-cell-color-using-ruby.html

**Comment by zdavatz** [comment]
Thank you for this input.
