### ISSUE TITLE
Adjacent cells in a column using formulas have their data deleted

### ISSUE THREAD

**Issue by forty9er** [zdavatz/spreadsheet#147]
I'm experiencing a problem where cells in a column have all their data deleted if two or more adjacent cells use formulas.

Here's the code:

```
require 'spreadsheet'
Spreadsheet.client_encoding = 'UTF-8'

def test

# open the spreadsheet
book = Spreadsheet.open 'test.xls'
sheet1 = book.worksheet 0

# the new data
a = 1
b = 2

# input the new data into the spreadsheet
sheet1[5, 1] = a
sheet1[5, 2] = b

# save to "-Modded" file in same folder. 
book.write 'test-Modded.xls'
end

test
```

The original file looks like this:
![1-before](https://cloud.githubusercontent.com/assets/13773335/9722734/e83080ca-55aa-11e5-825b-0276960ab4ff.png)

The result I want is this:
![2-after-desired](https://cloud.githubusercontent.com/assets/13773335/9722737/f38a5144-55aa-11e5-8264-e8b0dad16926.png)

but the actual result is this:
![3-after-actual](https://cloud.githubusercontent.com/assets/13773335/9722738/fe4cd50c-55aa-11e5-896b-481e9da96b6d.png)

test files, including an XLS file: 
https://www.dropbox.com/s/qblq7mcfy6cvc48/delete_error.zip?dl=0

**Comment by forty9er** [comment]
I should add that I'm using LibreOffice 4.4.4.3 to create and open the .XLS file.
I don't have Excel on my system.

**Comment by zdavatz** [comment]
Ok, this looks like a bug.

**Comment by zdavatz** [comment]
I get this, so all looks fine on my side with Ruby 2.2.2-p95. What Ruby Version are you using?
![modded](https://cloud.githubusercontent.com/assets/4953/9728372/9cbe35ee-5607-11e5-88bd-c278cef4869e.jpg)

**Comment by forty9er** [comment]
I'm also on 2.2.2-p95.

The behaviour you're getting is very strange, it's not even inputting "1" and "2" into the spreadsheet, so it seems from the screenshot that it's not doing anything at all.

**Comment by forty9er** [comment]
Actually by the looks of things your screenshot is the unmodified test file (ie. you haven't run delete_error.rb on it yet). I can tell because the last sentence in cell B4 is underlined and Spreadsheet removes this formatting (in itself, not a problem for me)!

**Comment by zdavatz** [comment]
sorry, uploaded wrong screen.

**Comment by forty9er** [comment]
OK. Note the behaviour when the formula in D7 is moved down to D8 and D7 has no formula in it - everything then works as it should. The problem only appears when there are two adjacent formulas in a column.
