### ISSUE TITLE
`worksheet[0]` and `worksheet.first` behave differently

### ISSUE THREAD

**Issue by dunn** [zdavatz/spreadsheet#152]
Given this `rows.rb`:

``` ruby
require "spreadsheet"

book = (Spreadsheet.open "#{ENV["HOME"]}/test/spreadsheet/test.xls")

book.worksheets.each do |sheet|
  sheet.each do |row|
    row.each_with_index do |cell, i|
      next if cell.nil?
      puts "#{sheet[0, i]}: #{cell.inspect}"
      puts "#{sheet.first[i]}: #{cell.inspect}"
    end
  end
end
```

And the following `test.xls`
![screen shot 2015-11-02 at 12 30 11 pm](https://cloud.githubusercontent.com/assets/985416/10894414/4bfef5c6-8163-11e5-839e-5bac9b26a416.png)

The expected output of `bundle exec ruby rows.rb` is

```
header: "header"
header: "header"
header: "celldata"
header: "celldata"
```

But the actual output is

```
: "header"
header: "header"
: "celldata"
header: "celldata"
```

**Comment by zdavatz** [comment]
What Ruby Version and what OS are you using? With what are you viewing the XLS file?

**Comment by dunn** [comment]
Ah, sorry. 
- Mac OS 10.11.1
- Excel 2011 14.5.7
- `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]`

**Comment by zdavatz** [comment]
Ok. Please try this with LibreOffice 5.0.x on Mac. Excel on Mac is not really supported.

**Comment by dunn** [comment]
Afraid to say I get the same result with LibreOffice 5.0.2.2.

**Comment by zdavatz** [comment]
Do you have a recommendation what there is to do as a solution?

**Comment by dunn** [comment]
> Do you have a recommendation what there is to do as a solution?

I just assumed the solution would be to make them behave the same.

**Comment by zdavatz** [comment]
You mean Excel for Mac and Windows?

**Comment by dunn** [comment]
I mean for `worksheet[0]` and `worksheet.first` to do the same thing.

**Comment by zdavatz** [comment]
you want a new method for that?

**Comment by zdavatz** [comment]
I will send you an invite to Slack so we can continue our discussion there.

**Comment by zdavatz** [comment]
How did you create this file: /test/spreadsheet/test.xls? Try creating the original file with Libreoffice and then modify it with your Ruby script. Will that help?

**Comment by dunn** [comment]
I'm not using this gem regularly anymore, so I'm not sure how much help I'll be.

**Comment by zdavatz** [comment]
ok!
