### ISSUE TITLE
Formats not working in Excel 2013 for Windows

### ISSUE THREAD

**Issue by varunDM** [zdavatz/spreadsheet#156]
On opening in MS Excel items beyond the 10th or 11th row looses its formats and are getting aligned incorrectly.

**Comment by InteNs** [comment]
what happend? i'm having this issue

**Comment by zdavatz** [comment]
What version of Excel do you use? Which OS?

**Comment by InteNs** [comment]
I've found this issue to be related to #120 
problem is i can't cache my formats because we're relying on the `update_format` method and can't use the `set_format` without a major refactor

**Comment by zdavatz** [comment]
What version of Ruby are you using! What OS?

**Comment by InteNs** [comment]
macOS 10.14
ruby 2.5.3
excel: office365 latest version via mac app store
