### ISSUE TITLE
how do i get cell with multiple font styling?

### ISSUE THREAD

**Issue by lukas2342** [zdavatz/spreadsheet#157]
hi,
i found this https://github.com/zdavatz/spreadsheet/issues/92 where u007 asked how to do it. it seems it was not possible back then. is it by now?

**Comment by zdavatz** [comment]
Check the guide. https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md

**Comment by lukas2342** [comment]
i am sorry i think i should have described what i want to do more carefully. i am trying to read from an existing excel document with more that one format per cell. in particular i have some words that are striked out. is it possible to find out what word in the cell is striked out?

**Comment by zdavatz** [comment]
I am sure this is possible with spreadsheet, but my guess is, that it is not yet supported in the current version.
