### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by timting** [zdavatz/spreadsheet#159]
Currently, rubygems is listing this under a MIT license, which doesn't seem accurate from what is in the repo. Is there a way you can change that?

**Comment by zdavatz** [comment]
Yep, that is not correct. Spreadsheet is going under the GPLv3.0 License.

**Comment by zdavatz** [comment]
Also it says GPLv3.0 in this file: https://github.com/zdavatz/spreadsheet/blob/master/spreadsheet.gemspec 

is something wrong with this file? Or does Rubygems interpret something wrong?

**Comment by brgordon1** [comment]
Hi Zeno!

We are interested in purchasing the commercial license for a confidential SaaS project that I'm working on.  I didn't see pricing information on the site (it just said "USD xxxx").  Could you help me with exact pricing and where to pay it?

Thanks!

**Comment by zdavatz** [comment]
Cool, send me an Email to 

```zdavatz@ywesee.com```

**Comment by brgordon1** [comment]
This is a follow-up to the Github post.  I'm interested in purchasing a commercial license for this gem.  I would primarily have a SaaS product but might have one on premise deployment.

Could you send me the pricing details?

**Comment by zdavatz** [comment]
Email sent.
