### ISSUE TITLE
Feature request - Add ability to insert comment to a cell

### ISSUE THREAD

**Issue by jobetdelima** [zdavatz/spreadsheet#163]
As per an email thread from the discussion group (https://groups.google.com/forum/#!topic/rubyspreadsheet/pZgPlhE5dLo), here's a request for this functionality to be added.

Looking forward to it!

**Comment by zdavatz** [comment]
Ok, lets hope someone else wants this feature as well.

**Comment by meta-manish-sharma** [comment]
hey zeno,
As you mentioned in above comment, i m also in a need of this feature.
Can you please estimate the time needed for this feature development. 

Looking forward for your positive response.

**Comment by zdavatz** [comment]
Sure. Do you want a quote?

**Comment by meta-manish-sharma** [comment]
yes, if you can please.

**Comment by zdavatz** [comment]
Ok, I just sent you a Mail.
