### ISSUE TITLE
Stream spreadsheet rows to file

### ISSUE THREAD

**Issue by pomartel** [zdavatz/spreadsheet#164]
It looks like the spreadsheet gem gathers all cells data in memory before outputting to a file. This can be problematic for big Excel files on memory constrained environments like Heroku. I was wondering if there is a way to stream directly to the file as rows are added and then free up that memory? I read in the source code that you can initialize a `Workbook` with a `io` object but I'm not sure if that's helpful.

**Comment by zdavatz** [comment]
You will have to try this by yourself. This may help you as well:
https://github.com/zdavatz/spreadsheet/blob/master/Excel97-2007BinaryFileFormatSpecification.pdf
https://github.com/zdavatz/spreadsheet/blob/master/excelfileformat.pdf

**Comment by pomartel** [comment]
Alright! Thanks for the quick answer!

**Comment by mcclone2001** [comment]
I know it's an old repo and an old question, but I'm working on some legacy code and having issues creating big files with this library,

@pomartel did you succeed in streaming the rows?
