### ISSUE TITLE
Clarify the scope and intent of those gem.

### ISSUE THREAD

**Issue by MrJoy** [zdavatz/spreadsheet#166]
It would be helpful if you could clarify both on RubyGems and in the README that this gem is only intended to address the older/legacy binary MS Office file formats -- and that you have no intention of supporting the current/future XLSX format.  I had to dig through the mailing list archives to realize this, which is not an ideal use of my time.  I'm guessing you get fairly routine questions about this as well, which is not an ideal use of your time.  Adding notes to the README and RubyGems would elide much of that wasted effort on both fronts.

**Comment by zdavatz** [comment]
Feel free to patch the README and send me a pull request.

**Comment by MrJoy** [comment]
1. I'm not *totally* clear on what you deem the scope of this gem to be, so I suspect whatever I stated would miss -- or misrepresent -- important distinctions.  I'm making a rough assessment based on skimming the mailing list.
2. Given the lack of licensing clarity I raised in my second issue, I'm uncomfortable contributing a patch even to the README as I'm not certain the published license is the license my contribution would be held to.

**Comment by zdavatz** [comment]
Ok, then do not supply a patch. The License of this gem is clear. It is GPLv3. Period.

**Comment by MrJoy** [comment]
Except you [seem to think](http://spreadsheet.ch/2014/10/24/using-ruby-spreadsheet-on-heroku-with-dynos/) the GPLv3 is the GNU AGPLv3 -- which it is not.

**Comment by zdavatz** [comment]
No, I do not think that. Spreadsheet gem is licensed under GPLv3.

**Comment by MrJoy** [comment]
Requiring a commercial license to run it on a public-facing server is inconsistent with the GPLv3.  The GNU AGPLv3 exists for that purpose.

**Comment by zdavatz** [comment]
see above.

**Comment by MrJoy** [comment]
Allow me to quote:  "In other words, this means that if your Software runs on Heroku, is not OpenSource and uses The Ruby Spreadsheet gem you will have to buy a NON-OpenSource Commercial License that allows you to use The Ruby Spreadsheet together with your closed-source code."

That is not how the GPLv3 works.  That is how the GNU AGPLv3 works.

**Comment by zdavatz** [comment]
This may be your valid opinion but it is not mine. Spreadsheet gem is licensed under GPLv3, period.

**Comment by MrJoy** [comment]
If you insist on claiming it's under the GPLv3 then you should stop trying to scare people into paying for licenses they do not need.

It benefits nobody for you to create a confusing legal situation.

**Comment by MrJoy** [comment]
Also, let's perhaps go for a more authoritative opinion on the matter:

[However, putting the program on a server machine for the public to talk to is hardly “private” use, so it would be legitimate to require release of the source code in that special case. Developers who wish to address this might want to use the GNU Affero GPL for programs designed for network server use.](http://www.gnu.org/licenses/gpl-faq.html#UnreleasedMods)

So, it is the opinion of the Free Software Foundation that your interpretation of the GPLv3 is incorrect.

**Comment by zdavatz** [comment]
I appreciate your opinion.
