### ISSUE TITLE
rails - passing xls file between methods

### ISSUE THREAD

**Issue by yardench** [zdavatz/spreadsheet#168]
I'm trying passing my xls file that I created to another method , but it gives me a lot of different error Well, my code look like this :
```
book = Spreadsheet::Workbook.new
sheet1 = book.create_worksheet


sheet1.row(0).push "Time", "Name", " Phone", "Email Adress"
@data.each_with_index do |d, i|
  sheet1.insert_row i+1, [ d.time, d.name, d.phone, d.email]
end
xlsExport.exporter(book)
book is my sheet name.


```

Thank you guys ahead !

**Comment by zdavatz** [comment]
Sorry, we can not support issues with Rails. I will close this but it should not stop you from posting as others may have a solution for your problem.
