### ISSUE TITLE
OLE2 Invalid Signature

### ISSUE THREAD

**Issue by mo3taz-abdallh** [zdavatz/spreadsheet#172]
Hello
 I have to download google sheet using google api client gem then using spreadsheet gem to read & write in this sheet but every time i try to open this sheet i faced the following issue 
**OLE2 Invalid Signature**
Note i have tried 2 mime :
MS Excel	application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
Open Office sheet	application/x-vnd.oasis.opendocument.spreadsheet

**Comment by zdavatz** [comment]
what software created that XLS file?

**Comment by markslemko** [comment]
I have the same problem.
mac version of excel

**Comment by zdavatz** [comment]
Mac version of XLS ist not really supported. Please use Libreoffice.
