### ISSUE TITLE
Trouble In Fancy Formatting Implementation Using Spreadsheet Gem

### ISSUE THREAD

**Issue by meta-manish-sharma** [zdavatz/spreadsheet#173]
While using spreadsheet gem i am facing trouble in fancy formatting of code snippet while reading data from xls file. 

For example  :

```
Main()
{
        int a = 0;
        while(a<5)
        {
                Sum(a);
                a++;
        }
}
void Sum(int a)
{
        static kk;
        printf(“%d”,kk+a);
        kk++;
}
```

While reading this code i am not able to maintain proper indentation of this code(spaces are removed).

Here is the file : 
[question-upload.xls.zip](https://github.com/zdavatz/spreadsheet/files/220360/question-upload.xls.zip)

**Comment by zdavatz** [comment]
Sorry, I do not have solution for this at the moment.
