### ISSUE TITLE
Incorrect values in unchanged worksheets

### ISSUE THREAD

**Issue by michal-konarski** [zdavatz/spreadsheet#180]
Hi!

I've got a spreadsheet created in LibreOffice 5.1.3.2. It contains two worksheets with some values. I prepared a Ruby script that:
1. opens the spreadsheet
2. changes some values in the **first** worksheet only
3. saves the spreadsheet to separate file

As a result the output file has correct values in the first worksheet, but the second worksheet (which should be left untouched) now has mixed values from itself and the first worksheet. 

The code:
```
require 'spreadsheet'

sheet = Spreadsheet.open('sheet.xls')
sheet.worksheet(0).row(0)[0] = 'new'
sheet.worksheet(0).row(1)[0] = 'new2'
sheet.write('out.xls')
```

Example:
[xls_bug.zip](https://github.com/zdavatz/spreadsheet/files/414998/xls_bug.zip)

In the second worksheet it should have values:
![screen shot 2016-08-12 at 11 27 21](https://cloud.githubusercontent.com/assets/10550838/17618415/f8a7a7fe-607f-11e6-97d6-fff32697884d.png)

But it has:
![screen shot 2016-08-12 at 11 27 30](https://cloud.githubusercontent.com/assets/10550838/17618435/1385c826-6080-11e6-90a4-527f4344db2a.png)

I tried the latest version of `spreadsheet` (1.1.3) @ Ruby 2.0.0, 2.1.5, MacOS X, Linux.

Thanks in advance!

**Comment by zdavatz** [comment]
what makes you think saving two worksheets at the same time should work?

**Comment by michal-konarski** [comment]
@zdavatz what's wrong in thinking that `sheet.write` saves the entire spreadsheet with all its worksheets? Doesn't it work that way?

**Comment by zdavatz** [comment]
No it does not work that way. Please read the tutorial and start from there, step by step. https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md

**Comment by michal-konarski** [comment]
@zdavatz I've already implemented working solution with opening and saving of multiple-worksheet spreadsheets using your library and I've read this tutorial at least 6 times, also step by step. The section that is relevant in this case is "Modifying an existing Document" and I honestly don't know what did I do incorrectly. 

The sample that you provide there is:
```
book = Spreadsheet.open '/path/to/an/excel-file.xls'
sheet = book.worksheet 0
sheet.each do |row|
  row[0] *= 2
end
book.write '/path/to/output/excel-file.xls'
```

which can be used in my code as:
```
book = Spreadsheet.open 'sheet.xls'
sheet = book.worksheet 0
sheet.each do |row|
  row[0] = 'new'
end
book.write 'out.xls'
```

And that works, the second worksheet is left unmodified. However if, instead of iterating over the rows, I specify exactly which cell to modify, the second worksheet gets incorrect data:

```
book = Spreadsheet.open 'sheet.xls'
sheet = book.worksheet(0)
sheet.rows[0][0] = 'new'
sheet.rows[1][0] = 'new2'
book.write 'out.xls'
```

So, please point me what I'm doing wrong. There is not a single sentence in your guide about saving multiple spreadsheets at once.

**Comment by zdavatz** [comment]
Yes. True. This may just not yet be supported. Sorry.
