### ISSUE TITLE
I got different format when read the number from excel cells

### ISSUE THREAD

**Issue by wxy1106** [zdavatz/spreadsheet#181]
I made some random integer numbers with different digit (from 1 to 16).

Note that I didn't change any format of the cells. So I think every number should show the same form when be printed.

![f80d tmp](https://cloud.githubusercontent.com/assets/18569573/17968829/7784ddae-6b01-11e6-973e-9370aee9f85b.jpg)

But when I printed them out in my ruby program through spreadsheet, I found different digit shows different format. 

![1](https://cloud.githubusercontent.com/assets/18569573/17968846/8aafa6b6-6b01-11e6-9f78-619743bd2bb9.png)
![2](https://cloud.githubusercontent.com/assets/18569573/17968873/b90313cc-6b01-11e6-87fc-edc85b96b746.png)

Here is what I found:

1. the 16-digits number is scientific notation
2. the 7 and 8-digits number always keep integer
3. the 6 and 9-digits number sometimes become float and keep integer in the rest case
4. the rest numbers are float form though they are integer original.

I just want to know is this a bug or an intentional feature.

**Comment by zdavatz** [comment]
What OS are you using? What version of the gem are you using? Can you please post the script that created the files of which you posted the screenshots. Thank you.

**Comment by wxy1106** [comment]
@zdavatz Sorry for missing the detials

I'm using spreadsheet-1.0.7, Excel 2013, and I saved the file as xls suffix.

[Here is the xlsx file](https://github.com/zdavatz/spreadsheet/files/439424/excel_test.xlsx), sheet2 shows how I create these numbers.

The problem exists both on Windows (win10/64bit) and Linux (Read Hat).

The rake task goes like this

```
namespace :excel do
  desc "excel_test"
  task excel_test: :environment do
    xls_path = Rails.root.join('tmp', 'excel_test.xls')
    book = Spreadsheet.open(xls_path)
    sheet = book.worksheet 0
    sheet.each do |row|
      row.each_with_index do |cell,index|
        puts "#{index+1}：#{cell}"
      end
    end
  end
end
```

I'm pretty sure these results are affected by the Excel. What format the cell treats a certain number causes different results.

But its still wired that not all the numbers have the same form when printed out, since I didn't change any format of any cell.

**Comment by zdavatz** [comment]
Can you please try the same with LibreOffice? Excel 2013 does have some issues. https://de.libreoffice.org/download/libreoffice-still/

**Comment by wxy1106** [comment]
@zdavatz 
Do you mean using LibreOffice to create the 'xls' file?
If so, I tried and got this:

![libre_test](https://cloud.githubusercontent.com/assets/18569573/18052620/f4e5c392-6e2d-11e6-96fd-7fedd7361f0c.png)

I think it's better than Excel. :smile:

**Comment by zdavatz** [comment]
Yes, I think LibreOffice is far better then Microsoft Office for this kind of stuff.
