### ISSUE TITLE
Formula does not get evaluated upon writing to file

### ISSUE THREAD

**Issue by dangnlg2** [zdavatz/spreadsheet#182]
I am currently trying to import a formula which add all the cells in a column together inside my code. After I added the formula to the bottom cell in the column, I opened the .xls file and saw the formula instead of the result. 

**Issue:**
<img width="253" alt="excel issue" src="https://cloud.githubusercontent.com/assets/20955453/18722275/1b096c00-7fe9-11e6-8586-3080c3d9602a.png">
<img width="253" alt="excel issue" src="https://cloud.githubusercontent.com/assets/20955453/18722283/24535820-7fe9-11e6-8c5b-77cb5de9520f.png">

Here's my formula in the bottom cell '=SUM(B5:B7)', the issue is that I see the exact formula when I open the file.

**Expected output:**

I expected to see the sum of the specified column instead of the formula.

I know that I can simply add all the number and store the result in my code, but I am more interested in getting the formula to work in excel.

Thank you in advance.

**Comment by zdavatz** [comment]
Please attach your sample script and your sample file. What version does your OS have and what version is your Ruby and what version is your gem.

**Comment by alduethadyn** [comment]
### I have the same issue. I'm using:
- Ruby 2.3.0
- OS X El Capitan 10.11.6
- Microsoft Excel for Mac 15.13.3 (150815)

### Code
```
require 'spreadsheet'

Spreadsheet.client_encoding = 'UTF-8'
book = Spreadsheet::Workbook.new

sheet = book.create_worksheet name: 'Test'

row0 = sheet.row(0)
(0..4).each { |n| row0[n] = 1 }
row0[5] = "=SUM(A1:E1)"

book.write("out.xls")
```

### Output
<img width="440" alt="screen shot 2016-11-27 at 11 07 56 pm" src="https://cloud.githubusercontent.com/assets/2507399/20656860/6634c034-b4f6-11e6-805d-9092b9432524.png">

**Comment by zdavatz** [comment]
Microsoft Excel for Mac does show strange behavior. Please test again with LibreOffice for Mac.

**Comment by alduethadyn** [comment]
Same results with LibreOffice

**Comment by zdavatz** [comment]
Ok, you will have to dig into the source code to fix this.

**Comment by hothero** [comment]
@zdavatz Have this problem been solved? or any ideas to prevent this problem? I got the same here.

**Comment by Looooong** [comment]
Some problem in LibreOffice 6.0.3.2
