### ISSUE TITLE
Adding column to a spreadsheet

### ISSUE THREAD

**Issue by dangnlg2** [zdavatz/spreadsheet#183]
Is there anyway to add a column to a worksheet?

I know there is a function called "insert_row(row#,data)", is there something similar to this but for columns?

If not, how can I add columns to my worksheet?

**Comment by zdavatz** [comment]
Did you read the Guide?

**Comment by dangnlg2** [comment]
Yes, I did not see anything about adding columns there. That is why I asked this question here.

**Comment by zdavatz** [comment]
My guess is you will have to rewrite the whole sheet with the new column.
