### ISSUE TITLE
unable to add bottom border to merged cells

### ISSUE THREAD

**Issue by parmindersingh1** [zdavatz/spreadsheet#184]
I am not able to set border (bottom ) of merged rows and cells, only bottom border is not displaying

format is
     border_format = Spreadsheet::Format.new :border=>:thin, :size => 8

Here is code, 

          data.merge_cells(term_in+3, 1+report_column_index, term_in+6,terms.count+1+report_column_index)
           4.times do |r|
            (terms.count+1).times do |c|
              data.row(term_in+3+r).set_format(1+report_column_index+c, border_format)
            end
          end
          data[term_in+3,1+report_column_index] = student_term_remark.remarks

**Comment by zdavatz** [comment]
Please post the full test code and sample file here.

**Comment by parmindersingh1** [comment]
i am using ubuntu 16.04, Now i fixed the problem by adding text string to cell here is code

    data.merge_cells(term_in+3, 1+report_column_index, term_in+6,terms.count+1+report_column_index)
       4.times do |r|
        (terms.count+1).times do |c|
          data.row(term_in+3+r).set_format(1+report_column_index+c, border_format)
         # added this line
          data[term_in+3+r,1+report_column_index+c] = ""
        end
      end
      data[term_in+3,1+report_column_index] = student_term_remark.remarks

**Comment by zdavatz** [comment]
Ok, cool thanks for sharing this with us!
