### ISSUE TITLE
xls file open using excel 2013, table not load properly

### ISSUE THREAD

**Issue by hendranata** [zdavatz/spreadsheet#185]
helo

i have a xls generated from this gem
but table border is not perfect..
when i open using ms excel 2007, it is working normal..all table are bordered properly.
but not for ms excel 2013.

how do we solved this? and how to generate excel with format xlsx ?

**Comment by hendranata** [comment]
https://s16.postimg.org/80yrygvk5/problem.jpg

here is the screenshot

**Comment by zdavatz** [comment]
Thank you. Use Libreoffice. MS XLS hat its issues.
