### ISSUE TITLE
how to use custom color

### ISSUE THREAD

**Issue by eccentricyan** [zdavatz/spreadsheet#192]
i want to use under color,
i read ```set_custom_color```, but i dont know how to use it.

```
:white_smoke = #F5F5F5

Spreadsheet::Format.new(base.merge({:pattern_fg_color => :white_smoke, :pattern => 1}))
```

**Comment by zdavatz** [comment]
ask this on the mailing list please.

**Comment by eccentricyan** [comment]
i resolve it.
http://stackoverflow.com/questions/33416887/how-to-use-custom-colors-in-the-spreadsheet-gem

**Comment by zdavatz** [comment]
Thanks for sharing the link!
