### ISSUE TITLE
Leap error in range 1/1/1900 - 28/1/1900

### ISSUE THREAD

**Issue by AlfonsoUceda** [zdavatz/spreadsheet#194]
Hi:

In my company we are using this gem to read and generate XLS files and we've noticed that there is an error handling a range of dates between 1/1/1900 and 28/1/1900.

There is an example for more context:
- Writing
```ruby
require 'spreadsheet'

book = Spreadsheet::Workbook.new
sheet1 = book.create_worksheet
sheet1.name = 'My First Worksheet'
sheet1[0,0] = DateTime.new(1900, 2, 28)
book.write 'excel-file.xls'

# You'll see 27/02/1900 in the excel file
```
- Reading
```ruby
require 'spreadsheet'

book = Spreadsheet.open 'excel-file.xls'
sheet1 = book.worksheet 0

sheet1.each do |row|
  puts row[0]
end

# You'll see 28/02/1900
```

Thank you for your time.

**Comment by zdavatz** [comment]
Thank you for reporting this. Let me know if you come up with a patch.

**Comment by zdavatz** [comment]
![date](https://user-images.githubusercontent.com/4953/44400114-565e8c80-a54a-11e8-8a8c-dc6b690eaed6.jpg)

**Comment by zdavatz** [comment]
This is what I get when I open the file with LibreOffice 6.0.5.2.
