### ISSUE TITLE
Formula type cells with values containing cross-sheet 'VLOOKUP's return @value of 0.00

### ISSUE THREAD

**Issue by dimanyc** [zdavatz/spreadsheet#195]
I have a 40-sheet xls file. Header rows are generated using a VLOOKUP reference to a couple of 'master sheets'. When I try to fetch `row.value` from cell with `Spreadsheet::Formula` type, I get `0.00` instead of actual formula returns. 

MS Excel, Google Speadsheet and OpenOffice Calc all return correct values calculated by the VLOOKUP.

**Comment by zdavatz** [comment]
Sample Script please with the output file.
