### ISSUE TITLE
Provide documentation showing correct installation of your gem

### ISSUE THREAD

**Issue by bigos** [zdavatz/spreadsheet#197]
require 'spreadsheet' gives me following error:

LoadError: cannot load such file -- spreadsheet

Some issues from the past give different solutions to the problem. The gem does not work out of the box.

**Comment by zdavatz** [comment]
1. Learn Ruby properly. 
2. Read the Guide: https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md
3. Stay friendly.

**Comment by bigos** [comment]
To stay friendly, I would suggest following changes specific to a Rails application.  Recommend using
    gem 'spreadsheet'
That solves lots of problems. When I put the above in my Gemfile the code worked and I was able to follow your examples. Sadly your gem has no support for Excel formulas yet, so I was forced to move to another gem. 

The fact that someone points out a problem should not be taken personally. I do not mean to criticise you.

**Comment by zdavatz** [comment]
I do not care about Rails.

**Comment by bigos** [comment]
I understand, but it seems that many Rails users will look at your gem and someone will open the same issue unnecessarily. Clarifying the documentation a tiny bit does not require much effort and would be helpful. Many gems try to solve this issue by including examples for pure Ruby and Rails. Some of those examples might be suitable for you. If it stops people like me from opening issues it might be worth your time.
