### ISSUE TITLE
RGB color assignments for a cell 

### ISSUE THREAD

**Issue by kannannadarajan** [zdavatz/spreadsheet#200]
Hi,

Is there any option to set custom RGB color as background color for a cell or row ? 
sheet.row(0).set_custom_color(41,63,108,175)
sheet.row(0).col(0).set_custom_color(41,63,108,175)

I would be great if you can guide me. 

Thanks,
Kannan

**Comment by zdavatz** [comment]
https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md

**Comment by UlyssesZh** [comment]
So how? We cannot fill in RGB values. We can only fill in a limited set of preset colors.

https://github.com/zdavatz/spreadsheet/blob/0f860fbd4f457f51331c873603efc4d5f7d5dc94/lib/spreadsheet/datatypes.rb#L13-L15
