### ISSUE TITLE
Is LibreOffice supported?

### ISSUE THREAD

**Issue by shevegen** [zdavatz/spreadsheet#201]
Is LibreOffice supported? That is, the part of LibreOffice that can create spreadsheets.

I have some text that I know how to turn manually into a spreadsheet; really a simple operation... some headers, some different colours per header column - that's it.

The current Readme says Microsoft spreadsheets. Could this be made a bit more clear whether this includes LibreOffice or not? Thanks!

**Comment by zdavatz** [comment]
only .xls is supported.
