### ISSUE TITLE
Make console output less verbose

### ISSUE THREAD

**Issue by Richard-Degenne** [zdavatz/spreadsheet#208]
When using Spreadsheet in a console (when debugging for instance), the output produced by a simple `Spreadsheet.open` is humongous. And there are lots of other calls that produce way too much output.

I know I can do `Spreadsheet.open(file); nil` to shut it off, but it's not clean, imo.

**Comment by zdavatz** [comment]
;) - let me know if you come up with a patch that works and that makes all the tests pass. I personally never use IRB.
