### ISSUE TITLE
Freezes Rspec

### ISSUE THREAD

**Issue by shen-sat** [zdavatz/spreadsheet#210]
Hi, I'm a code newbie, and this is the first time I'm reporting an issue, so please forgive me if I haven't worded/structured this properly!

I'm using TDD (with Rspec) to write some code. When I 'require' the spreadsheet gem in my code and run 'rspec' from my console, the test freezes. When I replace spreadsheet gem with any other gem, the test doesn't hang.

Not sure what the problem is, but thought it was worth flagging in case anyone else is having the same issue.

**Comment by zdavatz** [comment]
Thanks, interesting. I have no idea at the moment. Please keep me posted.

**Comment by shen-sat** [comment]
Will do! And thanks for making the gem - I'm using it to access a spreadsheet of dialogue for a game I'm making. Apart from said issue, it works great :)

**Comment by shen-sat** [comment]
Hi again! I'm going to close this issue, as I've found out that rspec freezes because of a fault in my own code: one of my tests returns the entire spreadsheet instead of a single cell; rspec looked like it was freezing on this test, when in fact it was busy calculating 100s and 100s of cells by mistake!

**Comment by zdavatz** [comment]
good to know, thank you for reporting the issue.
