### ISSUE TITLE
Percentage format

### ISSUE THREAD

**Issue by dsounded** [zdavatz/spreadsheet#212]
Hello, thanks for the gem, currently I can't find a proper way to set the Excel percentage format to the column, only `percentage_format = Spreadsheet::Format.new(number_format: '##0.00%')`. I use this for now, any other options(e.g. DSL for setting this). But even with the mask it gives wrong calculation...

**Comment by zdavatz** [comment]
Use the mailing list to ask this question.

**Comment by dsounded** [comment]
@zdavatz I tried but there is not response :(

**Comment by zdavatz** [comment]
Did you also check Stackoverflow?

**Comment by adrianmann** [comment]
I am looking for a solution for this also. I have asked an SO question here with no response as of yet: https://stackoverflow.com/questions/49899882/ignore-number-stored-as-text-warning-rails

**Comment by zdavatz** [comment]
Ok, thanks for reporting this!

**Comment by adrianmann** [comment]
I got an answer here: https://stackoverflow.com/q/49916286/1945948 (the first comment) combined with: `percent_format     = Spreadsheet::Format.new :number_format => '#0 %'`.

**Comment by zdavatz** [comment]
Cool, great, thank your for linking the Issue here.
