### ISSUE TITLE
Formula is missing randomly.

### ISSUE THREAD

**Issue by safiir** [zdavatz/spreadsheet#218]
## Desc
I try to open a excel file, then fill it with some dynamic data, but after the cell is filled and the excel is written to disk, some formula type cell's formula could be missing randomly.
## Environment:
Ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
Spreadsheet (1.1.5)
##  Code And File
> [script for test](https://gist.github.com/safiir/749abdc7d95c0dab0332421d3915c6d2)
> [.xls file for test](https://drive.google.com/open?id=1-RNP0vcCT__x4Glb4Xj-e-hk5pFe0GMV)

**Comment by zdavatz** [comment]
Interesting. Please provide sample code and file.

**Comment by safiir** [comment]
@zdavatz The test code and the file have been added. please check it, thanks!

**Comment by zdavatz** [comment]
Thanks. But we do not support XLSX. I will need an XLS File to test. Also: what software created the original XLS file?

**Comment by safiir** [comment]
@zdavatz Sorry, I updated the code and the file again, and I created the .xls file in WPS(like Microsoft Excel) for Debian-like Linux.

**Comment by zdavatz** [comment]
Try creating the file using LibreOffice or OpenOffice, the it should work. I have no idea what WPS is. They probably do not attend to all the format Rules of MS Excel. It makes a big difference to which software created the original file.

**Comment by zdavatz** [comment]
The output file "filled.xls" is not missing any data AFAICT.

**Comment by safiir** [comment]
@zdavatz The formula in power column is missing instead of current and previous data.

**Comment by zdavatz** [comment]
I guess you have to write that as well when writing the new file.

**Comment by zdavatz** [comment]
Have you tried to write the formulas from one cell to another?
