### ISSUE TITLE
How to attach note/comment to a particular cell in Ruby Spreadsheet? 

### ISSUE THREAD

**Issue by rajanmodi** [zdavatz/spreadsheet#224]
Spreadsheet.client_encoding = 'UTF-8'
book = Spreadsheet::Workbook.new
sheet = book.create_worksheet(:name => "Test")
sheet.row(0)[0] = "Rajan"                                                    # putting value in 0th row and 0th column
comment = Spreadsheet::Note.new                                   #Creating Note object 
comment.objID = 0 .                                                            #Initialising instance variables of Note class
comment.row = 0
comment.col =0
comment.text = "Some Comment"

#ToDo -  How to attach this note to a particular cell(0th row and 0th column)?

**Comment by zdavatz** [comment]
Good question. I do not know if this is implemented. I do not think so. Please let me know if you succeed.
