### ISSUE TITLE
More specifics in changelog?

### ISSUE THREAD

**Issue by henrik** [zdavatz/spreadsheet#229]
Hi! I noticed that the changelog entries for the last two versions (1.1.9 and 1.2.0) just say that new versions have been released: https://github.com/zdavatz/spreadsheet/blob/master/History.md

I can change the commit history to see what happened specifically, but I would have found it even more helpful if I could find that info summarised in the changelog :)

**Comment by zdavatz** [comment]
Feel free to summarize it and send me a pull request only for the history file

**Comment by zdavatz** [comment]
My thought is: if you are interested in more details, then use "git log"

**Comment by zdavatz** [comment]
But I am open to any Pull Requests that update the History.md file.

**Comment by henrik** [comment]
I find changelogs useful to easily see what changed from version to version. The commit history is often lower-level and may not directly say if something is backwards incompatible and so on.

So personally I would love for all projects to have them, but if you feel differently I won’t argue :)

**Comment by zdavatz** [comment]
I do not feel differently. But it is all a matter of time and priorities. Somebody has to do it.
