### ISSUE TITLE
Unclear message if argument if frozen

### ISSUE THREAD

**Issue by cyrilchampier** [zdavatz/spreadsheet#234]
When you try to open a spreadsheet from a stringio, the underlying string must be mutable:

```
> ::Spreadsheet.open(StringIO.new('0123'.freeze), 'rb+')
FrozenError: can't modify frozen String
from gems/spreadsheet-1.2.3/lib/spreadsheet/excel/reader.rb:1280:in `force_encoding'
```
https://github.com/zdavatz/spreadsheet/blob/master/lib/spreadsheet/excel/reader.rb#L1279

It would be cool if it was possible to open a frozen io.

**Comment by zdavatz** [comment]
Yes indeed! Please let me know if you come up with a patch.

**Comment by cyrilchampier** [comment]
Would this PR be ok for you?
https://github.com/zdavatz/spreadsheet/pull/235

**Comment by zdavatz** [comment]
All tests are failing. The tests need to pass, all of them.

**Comment by cyrilchampier** [comment]
Of course, I will fix that ;)
What do you think about support of ruby 1.8?
Do I fallback to previous behaviour (which fails on frozen steams)?

**Comment by zdavatz** [comment]
Yes, I think that is best, if you do not have another solution.

**Comment by cyrilchampier** [comment]
It should be good now.

**Comment by zdavatz** [comment]
Thank you, Version 1.2.4 is out. Please test.

**Comment by cyrilchampier** [comment]
Tested on my side, it is working!
Thanks for your reactivity.

**Comment by zdavatz** [comment]
thank you too!
