### ISSUE TITLE
Mention XLSX unsupported in README?

### ISSUE THREAD

**Issue by tom-lord** [zdavatz/spreadsheet#236]
A [common question](https://github.com/zdavatz/spreadsheet/search?q=xlsx+support&unscoped_q=xlsx+support&type=Issues) raised in this gem (and sometimes on [other forums](https://stackoverflow.com/q/56360671/1954610)) is: "Does this project support xlsx?"

The answer is, understandably, **no**.

But can I suggest making this clearer in the README?

**Comment by tom-lord** [comment]
On a related note, the README currently says:

> Spreadsheet supports Ruby 1.8.6, 1.8.7, 1.9.2, 1.9.3, 2.0.0, 2.1.1, 2.2.2

But it's actually [tested](https://github.com/zdavatz/spreadsheet/blob/e039d562395c478b48ad46eee2c39a15f37b620b/.travis.yml#L12-L21) against versions 1.8.7 - 2.6.1

**Comment by zdavatz** [comment]
Good point, thank you for noting. Can you send me a Pull-Request to update the README?
