### ISSUE TITLE
Microsoft Office : Protected View

### ISSUE THREAD

**Issue by AhmedKamal20** [zdavatz/spreadsheet#237]
Recently i used  the spreadsheet gem to generate a report on my rails app
But, when i open the result file with Microsoft Office, i get this warning :
 
![](https://support.content.office.net/en-us/media/3e94e9e7-a555-40d0-8ba1-1e43013d5c2b.png)
> "Office has detected a problem with this file. Editing it may harm your computer. Click for more details."

According to [this support article from Microsoft ](https://support.office.com/en-us/article/what-is-protected-view-d6f09ac7-e6b9-4495-8e43-2bbcdbcb6653)
> File validation failure   - When you see a message in Protected View that says "Office has detected a problem with this file. Editing it may harm your computer. Click for more details.", the file didn’t pass file validation. File validation scans file for security problems that can result from changes in the file structure.

So, Does anyone know how to solve this ? 

Thank you,

**Comment by zdavatz** [comment]
which Version of office, which OS (& Version) are you using?

**Comment by AhmedKamal20** [comment]
Sorry for not including that in the post.

Server :
- Ruby : 2.6.0
- Rails : 5.2.2
- Spreadsheet : 1.2.3

Client :
- Windows 8 & 10, Mac
- Office : 2013 & 365

**Comment by zdavatz** [comment]
Well Office for Mac does have some issues. Try opening your generated file with LibreOffice.

**Comment by AhmedKamal20** [comment]
It works without Issues on LibreOffice on Linux, but most of my users use Office on Windows.

Anyway, Thank you. 

And if any one know how to solve this in the future, please mention me.
