### ISSUE TITLE
Editing document leaves formulas stale.

### ISSUE THREAD

**Issue by westonstewarttennes** [zdavatz/spreadsheet#241]
It seems like there's no way to edit a document's cells that are used in formulas elsewhere in the same document.  When I try to open the document after editing I get a 'File error: data may have been lost.' error and I have to manually refresh all formulas.  Is there any way around this currently?

**Comment by zdavatz** [comment]
Can you please post specifics about what you are exactly doing? Code sample, OS Version, Ruby Version, LibreOffice/MSOffice Version, etc.

**Comment by westonstewarttennes** [comment]
Figured it out -- sheet had formulas set to update manually instead of automatically, in case anyone else stumbles on the same issue.

**Comment by zdavatz** [comment]
Thank you for documenting this.
