### ISSUE TITLE
Default columns number less then 5

### ISSUE THREAD

**Issue by vergilet** [zdavatz/spreadsheet#244]
I want to generate new XLS file with 3 column, but it generates 5 columns.
Can anyone help me with this? Are there any options to set that?
Thanks.

**Comment by zdavatz** [comment]
Have you read this? https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md

**Comment by vergilet** [comment]
Can you point me at exact place in the GUIDE?

**Comment by zdavatz** [comment]
Does this help you: https://stackoverflow.com/questions/39986323/ruby-spreadsheet-getting-column-count-in-xls-file/39986936

**Comment by vergilet** [comment]
@zdavatz, 

Sorry, maybe I have described my case unclearly.
To generate a new XLS I use the following code:

```ruby
    book = Spreadsheet::Workbook.new
    sheet = book.create_worksheet
 
    header = ['col_1, 'col_2', 'col_3']
    sheet.row(0).concat(header)
 
    spreadsheet = StringIO.new
    book.write(spreadsheet)

    spreadsheet.string
```

I am expecting to receive the next screen: 
<img width="380" alt="Знімок екрана 2019-09-14 о 22 20 28" src="https://user-images.githubusercontent.com/2478436/64912849-dfd89200-d73d-11e9-977e-db3b8026e27e.png">

But I receives table with two extra columns:
<img width="579" alt="Знімок екрана 2019-09-14 о 22 21 48" src="https://user-images.githubusercontent.com/2478436/64912868-1f9f7980-d73e-11e9-9767-8e5222981e82.png">

The only solution I came up is to merge column 3 with 4th and 5th:
```ruby
sheet.merge_cells(0, 2, 0, 4)
```

But I believe I am missing something.
Any suggestions?
Thanks.

**Comment by zdavatz** [comment]
with which software do you open the file?

**Comment by vergilet** [comment]
I use Numbers App (https://www.apple.com/uk/numbers/)
Now I see that it could be the problem with software.

Thanks for help!
Closing it.

**Comment by zdavatz** [comment]
Try LibreOffice.
