### ISSUE TITLE
File `xls` styles not appearing if open by google doc

### ISSUE THREAD

**Issue by Saleh-Salem** [zdavatz/spreadsheet#247]
I am working in export file type Xls, using Ruby on Rails(5.2), I exported by spreadsheet gem (1.2.5).
After the export file, the file is open in LibreOffice with styles, but when opening in a google doc or Microsoft office excel not showing styles.

**Comment by zdavatz** [comment]
Are you using Office on Mac or Windows?

**Comment by Saleh-Salem** [comment]
office in windows
