### ISSUE TITLE
Complex Excel Structure -> Cells location jumbled upon saving

### ISSUE THREAD

**Issue by sergio-rivas** [zdavatz/spreadsheet#259]
When parsing a complex structure excel file (i.e. lots of merges, etc), then modifying a few specific cells, the output file changes the cell locations of many unrelated cells around the sheet (both row/column position are being shifted for other cells). 

Is there anything I should provide to help you be able to replicate the issue?

**Comment by zdavatz** [comment]
what software created the original file?

**Comment by sergio-rivas** [comment]
Microsoft Excel, it's a .xls file too.  I think it might have to do with the fact that the file has many use of vertical merges.

**Comment by zdavatz** [comment]
Please try to open and save the file with LibreOffice and then try to edit it again using spreadsheet. Does that work?

**Comment by zdavatz** [comment]
Did you save the file as UTF-8? Which version of LibreOffice and which OS are you using?

**Comment by sergio-rivas** [comment]
LibreOffice 7.1.0.3, Mac OSX.

There is no option to choose UTF-8 when saving as xls.

<img width="412" alt="Screen Shot 2021-03-02 at 1 23 08 AM" src="https://user-images.githubusercontent.com/25148614/109612839-ef949380-7af5-11eb-95df-376d801c039d.png">

**Comment by zdavatz** [comment]
Please share the Ruby script with which you want to open the file.

**Comment by sergio-rivas** [comment]
I tried digging into the code myself, but was unable to get anywhere. Is there a way to know exactly what encoding LibreOffice is using when saving? I tried MACROMAN, but would get invalid byte sequence errors, I tried UTF-8, and didn't get invalid byte sequence errors, but in BIFF8, it kept encountering a lot of errors due to nil values here and there.

**Comment by zdavatz** [comment]
For me the question is which language/character uses that "strange" characterset in your XLS?

**Comment by sergio-rivas** [comment]
It's all alphanumeric characters. 

I even tried running a macros to enforce all alphanumeric characters only. 

```
REM  *****  BASIC  *****
Function AlphaNumericOnly(strSource As String) As String
    Dim i As Integer
    Dim strResult As String

    For i = 1 To Len(strSource)
        Select Case Asc(Mid(strSource, i, 1))
            Case 32 To 32, 48 To 57, 65 To 90, 97 To 122: 'include 32 if you want to include space
                strResult = strResult & Mid(strSource, i, 1)
        End Select
    Next
    AlphaNumericOnly = strResult
End Function

Function CleanSheet(sheetName As String) As Boolean
	Dim sh As Object, z As Object, c As Object
    Dim qCells As Object, enuCells As Object
    sh = ThisComponent.Sheets.getByName(sheetName)
    z = sh.getCellRangeByName("A1:U300")
    qCells = z.queryContentCells(-1)
    enuCells = qCells.Cells.createEnumeration
    Do While enuCells.hasMoreElements
      c = enuCells.nextElement
      If Left(c.Formula, 1) = "=" Then 
		
      Else
		c.string = AlphaNumericOnly(c.String)
	  End If  
    Loop
    CleanSheet = true
End Function


Sub CleanAll()
	CleanSheet("GRID")
	CleanSheet("RESULTS")
	CleanSheet("PICTURES")
End Sub
```

**Comment by zdavatz** [comment]
Which Windows Version and which MS Excel Version created the orginial file? Can these people try to create the same file using LibreOffice on Windows?

**Comment by sergio-rivas** [comment]
Can I send you the LibreOffice saved .xls file and have you take a look or have you copy/paste the sheets to a new libreoffice file? Would charts or images affect the ability to read the sheet?

**Comment by sergio-rivas** [comment]
After some messing around with different settings, the following combination fixed my issue:

1. Uncheck "Protect Sheet"
2. Uncheck "Protect Spreadsheet Structure"

<img width="339" alt="Screen Shot 2021-03-13 at 1 43 52 PM" src="https://user-images.githubusercontent.com/25148614/111042284-4c4f5280-8402-11eb-830b-5fb071fa3950.png">

**Comment by zdavatz** [comment]
Ok, good to know, thank you for reporting!
