### ISSUE TITLE
Read/write background colors of cells or rows?

### ISSUE THREAD

**Issue by dancaugherty** [zdavatz/spreadsheet#26]
This might already exist, but it's not obvious to me (as of version 0.7.7).

I'd like to be able to get/set the background color of a cell or row. I noticed there is some level of support for background colors in the Spreadsheet::Format class, but I'm not sure if it's used or set in any way.

(For what it's worth, I did clone the repository and poke around, and I realized the XLS format is _not_ pleasant terrain for newbies.)

**Comment by railsfactory-madhusudhan** [comment]
by dancaugherty's reply I am able to get 'yellow', but I need to read 'yellow2' color which is not coming and not for any other colors. Is there a way to read color's of columns? Any help will be appreciated.

**Comment by zdavatz** [comment]
Have you read this: https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md

**Comment by railsfactory-madhusudhan** [comment]
I went through the link, but there is no info regarding getting the bg color of cell or methods. Can you please be more specific?
I am using sheet1.row(0).format(1).pattern_fg_color.to_s to get the color of a cell.

**Comment by zdavatz** [comment]
Did you google? This should help you for setting the background color in XLS files with the Ruby Spreadsheet: http://stackoverflow.com/questions/7730112/ruby-spreadsheet-row-background-color

**Comment by mariogalvez17** [comment]
Hi!, first. i need to say "Great gem my firend", second.... I have used the colors defined in the gem before and have been sufficient for me, but now, I work in an app where users generates custom indicators of certain attributes, they wants the generated report in xls to contain those colors as background .... It is possible to do the color assignment through the RGB code dynamically??

PD: google translator help me out to "write" this

**Comment by zdavatz** [comment]
should be possible, but will take time. You want to pay for the development of this feature?
