### ISSUE TITLE
No read Excel rows more then 65353

### ISSUE THREAD

**Issue by Sega100500** [zdavatz/spreadsheet#264]
No read rows from Excel more than 65535
I have Excel with rows ~88000 rows. Process stop after read row 65535 (unsigned int 2 bytes)

**Comment by zdavatz** [comment]
1. Ok, interesting. 
2. What platform are you on? Windows, Mac, Linux? 
3. Which Ruby version?
4. Can you share some code and the file?
5. Can you open the file with LibreOffice, save it and try again?

**Comment by Sega100500** [comment]
Most likely, this is a limitation of Excel 97-2003, *xls* extension 

> 1. Ok, interesting.
> 
>     2. What platform are you on? Windows, Mac, Linux?
> 
>     3. Which Ruby version?
> 
>     4. Can you share some code and the file?
> 
>     5. Can you open the file with LibreOffice, save it and try again?

**Comment by Sega100500** [comment]
Most likely, this is a limitation of Excel 97-2003, *xls* extension 

> 1. Ok, interesting.
> 
>     2. What platform are you on? Windows, Mac, Linux?
> 
>     3. Which Ruby version?
> 
>     4. Can you share some code and the file?
> 
>     5. Can you open the file with LibreOffice, save it and try again?

**Comment by zdavatz** [comment]
Yes, that is what I also thought. Thank you.
