### ISSUE TITLE
spreadsheet generates invalid xls on ruby 2.0.0

### ISSUE THREAD

**Issue by alexeyramazanov** [zdavatz/spreadsheet#32]
xls files generated by spreadsheet on ruby 2.0.0 are broken.

For example this code generates valid xls on 1.9.3, but not on 2.0.0

``` ruby
require 'spreadsheet'
book = Spreadsheet::Workbook.new
sheet = book.create_worksheet
sheet[0,0] = 'text'
book.write 'file.xls'
```

https://dl.dropbox.com/u/937160/ruby/file193.xls
https://dl.dropbox.com/u/937160/ruby/file200.xls

```
ruby 2.0.0p0 (2013-02-24 revision 39474) [i686-linux]
rubygems 2.0.0
spreadsheet 0.8.1
```

**Comment by joshuapinter** [comment]
That's weird, we're using `spreadsheet` gem on Ruby 2.3.6 with no issues:

```bash
$ ruby -v
ruby 2.3.6p384
(2017-12-14 revision 61254) [x86_64-darwin17]
```

**Comment by zdavatz** [comment]
That was an old post you are commenting on ;).

**Comment by joshuapinter** [comment]
@zdavatz  👍 😃  Your gem has been very good for us for the last 7 years. We need support for 100,000+ rows now so we're moving to another gem in order to support `.xlsx` format. Just wanted to say a quick thanks. 🙏
