### ISSUE TITLE
Support for Ruby 2.0

### ISSUE THREAD

**Issue by mechiland** [zdavatz/spreadsheet#39]
Now ruby 2.0 is ready for production. I have tested that only 0.7.7 support ruby 2.0, all the later versions > 0.7.7 doesn't support Ruby 2.0.

**Comment by canoeberry** [comment]
Hate to ask, but if this runs in Ruby 2.0, who does the main page say 1.9.3?

**Comment by zdavatz** [comment]
Link please.

**Comment by canoeberry** [comment]
Whoa - it was in the main readme. But now it's fixed. So either I hallucinated it or you fixed it. Sorry for the trouble!

**Comment by zdavatz** [comment]
I fixed it. Thanks for the hint!
