### ISSUE TITLE
unexpected floats

### ISSUE THREAD

**Issue by masukomi** [zdavatz/spreadsheet#41]
We have a problem we keep encountering here where "GENERAL" excel cells filled with string integers will get be read as floats. It is repeatable but I don't have an isolated test case i could upload yet. In practice it will convert every row of a given column to floats (in today's case it's the first column), but it does not convert _all_ GENERAL columns populated with integers to floats. 

This is a real problem for us because we're reading rows in from the spreadsheet and using the improperly converted column to match the data in the spreadsheet up with our database and the excel row with 123.0 does not match the "123" entry in the database (not surprising). 

Is there some option we can toggle to make it stop trying to be smart about how it parses the data. We'd be perfectly happy if we could get it to just treat everything as a string and let us deal with converting it to the right type. Alternately, is there a way to tell it how to interpret the format on specific columns, or cells?

**Comment by johnmaxwell** [comment]
I got here, because I'm seeing the same behavior and had the same problem: spreadsheet is representing numeric input of a General cell/column as a Float instead of a String.  "123456" for example, becomes 123456.0. In my case, formatting the problematic cells and column as Text does not fix the issue. Spreadsheet continues to reify the value as a Float, so I implemented something like this:

  if number.is_a?(Float) && (number.to_i == number)
    number.to_i
  else
    number
  end.to_s

**Comment by johnmaxwell** [comment]
In fact, Excel even tries to "help" me convert it to an Number when it sees a cell that looks like a Number, but is of type Text:

![screenshot 2015-08-19 14 33 24](https://cloud.githubusercontent.com/assets/13686/9365409/644ebc0c-467f-11e5-896a-6a63ff20ab79.png)

**Comment by zdavatz** [comment]
thanks for sharing!

**Comment by ryanwjackson** [comment]
@masukomi @johnmaxwell Did you guys every find solutions for this?  I'm seeing the same issue even if you explicitly format the cells as text.  They still come out as 960.0 as opposed to "960".  Incredibly frustrating as we also can't dictate the content of the cells as we tell them to provide a random string ID, which to them in this case is "960" that keeps getting converted to a float.

**Comment by zdavatz** [comment]
What version of Office are you using?

**Comment by johnmaxwell** [comment]
@ryanwjackson It's been a year and that project is a distance memory, but I think that I implemented the [this workaround](https://github.com/zdavatz/spreadsheet/issues/41#issuecomment-132725639)
