### ISSUE TITLE
LoadError: cannot load such file -- spreadsheet/note

### ISSUE THREAD

**Issue by ciacka** [zdavatz/spreadsheet#67]
When I'm trying to load spreadsheet gem there's an above error.
I've searched issues history and found similiar problem where no relevant line was in Manifest.txt. I've made fix on forked repo but it's not working as expected.

https://github.com/kacperix/spreadsheet/commit/0e744d2dedd5efbf12be7995881510e64520bf24

After that in my Gemfile I've set:

`gem 'spreadsheet', git: 'git@github.com:kacperix/spreadsheet.git'`

Doesn't work.

**Comment by truptisalunkhe20** [comment]
Thank you so much the above solution to add gem 'spreadsheet', git: 'git@github.com:kacperix/spreadsheet.git'
