### ISSUE TITLE
Formulas don't calculated automatically in Microsoft Excel 2010

### ISSUE THREAD

**Issue by radanisk** [zdavatz/spreadsheet#71]
Steps to Reproduce:
1. Create new spreadsheet with formulas. Example:

```
row[7] = "=IF(F#{i + 9}=\"\";\"\";LEN(F#{i + 9}))"
```
1. Open spreadsheet in Microsoft Office Excel 2010.

Actual Results: Formulas don't calculated. It only calculated after I open cell for edit with double click and press Enter.

**Comment by JakeTheSnake3p0** [comment]
I'm having this same problem with MS Office 2003.

**Comment by hothero** [comment]
Is this issue solved?? I got the same problem here.
