### ISSUE TITLE
Open xlsx raise an Ole::Storage::FormatError

### ISSUE THREAD

**Issue by JuanitoFatas** [zdavatz/spreadsheet#77]
Hello! I have a problem on opening `xlsx` file.

Steps to reproduce:

Get this sample xlsx file to current folder:

``` shell
$ wget https://github.com/pkrumins/gnu-coreutils-cheat-sheet/raw/master/gnu-coreutils-cheat-sheet.xlsx
```

Open your interactive ruby shell or pry, paste this snippet of code:

``` ruby
require 'spreadsheet'
Spreadsheet.open './gnu-coreutils-cheat-sheet.xlsx'
```

yields:

```
Ole::Storage::FormatError: OLE2 signature is invalid
from /Users/Juanito/.rvm/gems/ruby-2.0.0-p353/gems/ruby-ole-1.2.11.7/lib/ole/storage/base.rb:378:in `validate!'
```

I am running on Mac OS X Mavericks 10.9.1 and using Ruby 2.0.0-p353.

Any ideas? Thanks!

**Comment by ramkarolis** [comment]
When is the support coming for XLSX?

**Comment by zdavatz** [comment]
won't be coming as far as I can tell. There are other gems out there that do that.

**Comment by rsazima** [comment]
Hey @zdavatz, thanks for the excellent gem! Is it hard to add support to the .xlsx? Do you accept contributions? Cheers

**Comment by zdavatz** [comment]
Of course I accept contributions but it will not be "easy" to ad XLSX support. But I am always open for patches. If you want to add XLSX support, look at the https://github.com/weshatheleopard/rubyXL gem first. We use that one.
