### ISSUE TITLE
File type not correctly identified using "file" command

### ISSUE THREAD

**Issue by russellsilva** [zdavatz/spreadsheet#97]
The standard *nix `file` command does not appear to identify spreadsheets created by `spreadsheet` correctly. Here's the results of running `file -b --mime-type` on the spreadsheet created by the gist [here](https://gist.github.com/phollyer/1214475):

```
$ file -b --mime-type test.xls
CDF V2 Document, No summary info
```

Whereas here's the result with an arbitrary `.xls` file I found on the internet:

```
$ file -b --mime-type QTL_Sample_data.xls
application/vnd.ms-excel
```

My guess is that additional metadata in the Excel-generated file as compared to the `spreadsheet`-generated file helps `file` correctly determine the type:

```
$ file test.xls
test.xls: CDF V2 Document, No summary info

$ file QTL_Sample_data.xls
QTL_Sample_data.xls: CDF V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Author: install, Last Saved By: Admin-Grisham, Name of Creating Application: Microsoft Excel, Create Time/Date: Mon Nov 19 18:38:23 2007, Last Saved Time/Date: Mon Jan 10 19:12:18 2011, Security: 0
```

Assuming I have correctly diagnosed the problem, is there any way to add this metadata to the created `.xls` files? I'm wondering about the "Name of Creating Application" field in particular as perhaps that will convince `file` that the file is an Excel file.

**Comment by Silox** [comment]
Thanks @extcode!
