### ISSUE TITLE
How to insert image in XLS using this spreadsheet gem

### ISSUE THREAD

**Issue by ponnusamygit** [zdavatz/spreadsheet#99]
Hi!
Is there any way to add image file into xls file, 
I did't find any method for that

**Comment by pomartel** [comment]
Hey @zdavatz! Thanks for this very useful gem. When you say "you can try", do you have an idea of how this could be done?

**Comment by zdavatz** [comment]
No, not at the moment. Do you want to submit a patch?

**Comment by frontandstart** [comment]
> Hey @zdavatz! Thanks for this very useful gem. When you say "you can try", do you have an idea of how this could be done?

I have request from my client to import/export xls with images and think that way with encode base64 will be work, but I think all this idea is seek :)

**Comment by zdavatz** [comment]
Let me know, once you have a Pull Request. Base64 encoded is a good idea for sure.

**Comment by frontandstart** [comment]
@zdavatz I find this one [activeadmin-axlsx](https://github.com/randym/activeadmin-axlsx) cover my 99% requirements. left only update to work with activeadmin >= 1.0.0  
and in this [PR](https://github.com/randym/activeadmin-axlsx/pull/32) @dubadub already start, I just use test and fix bugs with my active admin 1.4.x if they exist

**Comment by zdavatz** [comment]
ok.
